services:
  managerhttp:
    image: bretfisher/httpenv
    networks:
      - nginx_default
      - default
    #ports:
    #  - 8888:8888
    deploy:
      replicas: 3
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
networks:
  nginx_default:
    external: true
